M48
; DRILL file {KiCad 8.0.6} date 2025-05-08T21:12:25+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-08T21:12:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X135.875Y-62.345
X135.875Y-67.195
T2
X132.845Y-62.045
X132.845Y-67.495
M30
